version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - gosec
    - govet
    - misspell
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        # ST1005: error strings must be capitalized
        # QF1008: unneccessary use of embedded struct name before field
        # ST1012: error var should have name of the form ErrFoo
        text: "(ST1005:|QF1008:|ST1012:)"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - antrea.io/ofnet
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
